/**
 * EvidenceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidenceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EvidenceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EvidenceRepository,
} from "@oncepass/services/evidence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EvidenceRepositoryDdb } from "./evidence-repository.ddb.js";

/**
 * EvidenceRepositoryAdapter
 *
 * Implements EvidenceRepository port for infrastructure layer.
 */
export class EvidenceRepositoryAdapter implements EvidenceRepository {
  private readonly ddb: EvidenceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EvidenceRepositoryDdb(this.dynamoClient);
  }

  async listEvidence(input: Parameters<EvidenceRepository['listEvidence']>[0]): Promise<Awaited<ReturnType<EvidenceRepository['listEvidence']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEvidence(input);
  }

  async notariseEvidence(input: Parameters<EvidenceRepository['notariseEvidence']>[0]): Promise<Awaited<ReturnType<EvidenceRepository['notariseEvidence']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.notariseEvidence(input);
  }

  async getEvidence(input: Parameters<EvidenceRepository['getEvidence']>[0]): Promise<Awaited<ReturnType<EvidenceRepository['getEvidence']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getEvidence(input);
  }
}
