/**
 * SsiTemplateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SsiTemplateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SsiTemplateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SsiTemplateRepository,
} from "@oncepass/services/evidence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SsiTemplateRepositoryDdb } from "./ssi-template-repository.ddb.js";

/**
 * SsiTemplateRepositoryAdapter
 *
 * Implements SsiTemplateRepository port for infrastructure layer.
 */
export class SsiTemplateRepositoryAdapter implements SsiTemplateRepository {
  private readonly ddb: SsiTemplateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SsiTemplateRepositoryDdb(this.dynamoClient);
  }

  async getSsiTemplate(input: Parameters<SsiTemplateRepository['getSsiTemplate']>[0]): Promise<Awaited<ReturnType<SsiTemplateRepository['getSsiTemplate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSsiTemplate(input);
  }

  async updateSsiTemplate(input: Parameters<SsiTemplateRepository['updateSsiTemplate']>[0]): Promise<Awaited<ReturnType<SsiTemplateRepository['updateSsiTemplate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateSsiTemplate(input);
  }
}
