/**
 * Erasures DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Erasures Domain Module - Composition root
 *
 * DDD: Composition root for erasures domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ErasureRepositoryAdapter,
} from "@oncepass/adapters/erasures";
import { getIdGeneratorService } from "@oncepass/adapters";
import type { AdapterDynamoDBClient } from "@oncepass/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteExecuteVaultErasure,
  ExecuteGetErasureEvent,
  ExecuteListErasureEvents,
} from "@oncepass/services/erasures/usecases";
// Ports (interfaces)
import type {
  ErasureRepository,
} from "@oncepass/services/erasures/ports";

export interface ErasuresDomainModule {
  repos: {
    erasures: ErasureRepository;
  };
  useCases: {
    erasures: {
      create: ExecuteExecuteVaultErasure;
      get: ExecuteGetErasureEvent;
      list: ExecuteListErasureEvents;
    };
  };
}

export function buildErasuresDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ErasuresDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      erasures?: ErasureRepository;
    } = {};

    obj.erasures = new ErasureRepositoryAdapter(dynamoClient);
    return {
      erasures: obj.erasures!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    erasures: {
      create: new ExecuteExecuteVaultErasure(executionContext, idGenerator, repos.erasures),
      get: new ExecuteGetErasureEvent(executionContext, idGenerator, repos.erasures),
      list: new ExecuteListErasureEvents(executionContext, idGenerator, repos.erasures),
    },
  };
  return { repos, useCases: useCases as ErasuresDomainModule["useCases"] };
}
