/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@oncepass/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAccessDomainModule,
  buildConsentsDomainModule,
  buildErasuresDomainModule,
  buildEvidenceDomainModule,
  buildIdentityDomainModule,
  buildParticipantsDomainModule,
  buildVaultsDomainModule,
} from "../domains/index.js";
import type {
  AccessDomainModule,
  ConsentsDomainModule,
  ErasuresDomainModule,
  EvidenceDomainModule,
  IdentityDomainModule,
  ParticipantsDomainModule,
  VaultsDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private accessModule: AccessDomainModule | null = null;
  private consentsModule: ConsentsDomainModule | null = null;
  private erasuresModule: ErasuresDomainModule | null = null;
  private evidenceModule: EvidenceDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private participantsModule: ParticipantsDomainModule | null = null;
  private vaultsModule: VaultsDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get access domain module
   */
  getAccessDependencies(): AccessDomainModule {
    if (!this.accessModule) {
      this.accessModule = buildAccessDomainModule(this.dynamoClient);
    }
    return this.accessModule;
  }

  /**
   * Get consents domain module
   */
  getConsentsDependencies(): ConsentsDomainModule {
    if (!this.consentsModule) {
      this.consentsModule = buildConsentsDomainModule(this.dynamoClient);
    }
    return this.consentsModule;
  }

  /**
   * Get erasures domain module
   */
  getErasuresDependencies(): ErasuresDomainModule {
    if (!this.erasuresModule) {
      this.erasuresModule = buildErasuresDomainModule(this.dynamoClient);
    }
    return this.erasuresModule;
  }

  /**
   * Get evidence domain module
   */
  getEvidenceDependencies(): EvidenceDomainModule {
    if (!this.evidenceModule) {
      this.evidenceModule = buildEvidenceDomainModule(this.dynamoClient);
    }
    return this.evidenceModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get participants domain module
   */
  getParticipantsDependencies(): ParticipantsDomainModule {
    if (!this.participantsModule) {
      this.participantsModule = buildParticipantsDomainModule(this.dynamoClient);
    }
    return this.participantsModule;
  }

  /**
   * Get vaults domain module
   */
  getVaultsDependencies(): VaultsDomainModule {
    if (!this.vaultsModule) {
      this.vaultsModule = buildVaultsDomainModule(this.dynamoClient);
    }
    return this.vaultsModule;
  }

  clearAccessDependencies(): void { this.accessModule = null; }
  clearConsentsDependencies(): void { this.consentsModule = null; }
  clearErasuresDependencies(): void { this.erasuresModule = null; }
  clearEvidenceDependencies(): void { this.evidenceModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearParticipantsDependencies(): void { this.participantsModule = null; }
  clearVaultsDependencies(): void { this.vaultsModule = null; }

  getAccessDependenciesForRequest(): AccessDomainModule {
    return this.getAccessDependencies();
  }

  getConsentsDependenciesForRequest(): ConsentsDomainModule {
    return this.getConsentsDependencies();
  }

  getErasuresDependenciesForRequest(): ErasuresDomainModule {
    return this.getErasuresDependencies();
  }

  getEvidenceDependenciesForRequest(): EvidenceDomainModule {
    return this.getEvidenceDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getParticipantsDependenciesForRequest(): ParticipantsDomainModule {
    return this.getParticipantsDependencies();
  }

  getVaultsDependenciesForRequest(): VaultsDomainModule {
    return this.getVaultsDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.accessModule = null;
    this.consentsModule = null;
    this.erasuresModule = null;
    this.evidenceModule = null;
    this.identityModule = null;
    this.participantsModule = null;
    this.vaultsModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
