/**
 * Vault DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Vault DTOs
 *
 * DDD: Application DTOs for Vault use cases.
 */

import type { GetHomeVaultParams, ListHomeVaultsParams, RefreshHomeVaultCompletenessParams, RegisterHomeVaultRequestInput } from "@oncepass/core/vaults/types";

export type ListHomeVaultsInput = ListHomeVaultsParams;

export type RegisterHomeVaultInput = RegisterHomeVaultRequestInput;

export type GetHomeVaultInput = GetHomeVaultParams;

export type RefreshHomeVaultCompletenessInput = RefreshHomeVaultCompletenessParams;

export type ListHomeVaultsOutput = {};

export type RegisterHomeVaultOutput = {};

export type GetHomeVaultOutput = {};

export type RefreshHomeVaultCompletenessOutput = {};
