/**
 * ExecuteDecideConsentGrant - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDecideConsentGrant Use Case
 *
 * DDD: Application use case for get Decide.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DecideConsentGrantInput, DecideConsentGrantOutput } from "../dto/decide.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { DecideRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDecideConsentGrant {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly decide: DecideRepository
  ) {}

  async execute(input: DecideConsentGrantInput): Promise<DecideConsentGrantOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: decision
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).grantId) {
      throw new ValidationError("grantId is required");
    }
    const grantId = (input as any).grantId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.decide.decideConsentGrant({ grantId: grantId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${grantId}`);
    }

    return entity as DecideConsentGrantOutput;
  }
}
