/**
 * Evidence DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Evidence DTOs
 *
 * DDD: Application DTOs for Evidence use cases.
 */

import type { GetEvidenceParams, ListEvidenceParams, NotariseEvidenceRequestInput } from "@oncepass/core/evidence/types";

export type ListEvidenceInput = ListEvidenceParams;

export type NotariseEvidenceInput = NotariseEvidenceRequestInput;

export type GetEvidenceInput = GetEvidenceParams;

export type ListEvidenceOutput = {};

export type NotariseEvidenceOutput = {};

export type GetEvidenceOutput = {};
