/**
 * ErasureRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ErasureRepository Port
 *
 * DDD: Application port for erasurerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExecuteVaultErasureInput, ExecuteVaultErasureOutput, GetErasureEventInput, GetErasureEventOutput, ListErasureEventsInput, ListErasureEventsOutput } from "../dto/erasure.dto";
export interface ErasureRepository {
  listErasureEvents(input: ListErasureEventsInput): Promise<ListErasureEventsOutput>;
  executeVaultErasure(input: ExecuteVaultErasureInput): Promise<ExecuteVaultErasureOutput>;
  getErasureEvent(input: GetErasureEventInput): Promise<GetErasureEventOutput>;
}

export type { ExecuteVaultErasureInput, ExecuteVaultErasureOutput, GetErasureEventInput, GetErasureEventOutput, ListErasureEventsInput, ListErasureEventsOutput } from "../dto/erasure.dto";
