/**
 * Repository interface for AnomalyAlert
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AnomalyAlertEntity
} from "../models/anomaly-alert.entity.js";
import type {
  ListAnomalyAlertsParams
} from "../types/index.js";
/**
 * AnomalyAlertRepository Interface
 */
export interface AnomalyAlertRepository extends ReadRepository<AnomalyAlertEntity, string, ListAnomalyAlertsParams> {

}
