/**
 * Decide DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decide DTOs
 *
 * DDD: Application DTOs for Decide use cases.
 */

import type { DecideConsentGrantParams, DecideConsentGrantRequestInput } from "@oncepass/core/consents/types";

export type DecideConsentGrantInput = DecideConsentGrantParams & DecideConsentGrantRequestInput;

export type DecideConsentGrantOutput = {};
