/**
 * Handlers for AccessRequest
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AccessDomainModule } from "../dependencies/access-ddd.dependencies.js";
import type { GetAccessRequestInput, ListAccessRequestsInput, RequestEvidenceAccessInput } from "@oncepass/services/access";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/access-requests
 * Operation: listAccessRequests
 */
export async function listAccessRequests(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], grantId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AccessDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAccessRequestsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.requests.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/access-requests
 * Operation: requestEvidenceAccess
 */
export async function requestEvidenceAccess(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AccessDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RequestEvidenceAccessInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.requests.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/access-requests/{accessId}
 * Operation: getAccessRequest
 */
export async function getAccessRequest(
  request: FastifyRequest<{ Params: { accessId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AccessDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAccessRequestInput = {
    accessId: request.params.accessId,
  };
  const result = await deps.useCases.requests.get.execute(input);
  return reply.code(200).send(result);
}


