/**
 * Handlers for AmlDecision
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AccessDomainModule } from "../dependencies/access-ddd.dependencies.js";
import type { RecordAmlDecisionInput } from "@oncepass/services/access";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/access-requests/{accessId}/aml-decision
 * Operation: recordAmlDecision
 */
export async function recordAmlDecision(
  request: FastifyRequest<{ Params: { accessId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AccessDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordAmlDecisionInput = {
    accessId: request.params.accessId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.amlDecisions.get.execute(input);
  return reply.code(200).send(result);
}


