/**
 * AnomalyAlertRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnomalyAlertRepository Port
 *
 * DDD: Application port for anomalyalertrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListAnomalyAlertsInput, ListAnomalyAlertsOutput } from "../dto/anomaly-alert.dto";
export interface AnomalyAlertRepository {
  listAnomalyAlerts(input: ListAnomalyAlertsInput): Promise<ListAnomalyAlertsOutput>;
}

export type { ListAnomalyAlertsInput, ListAnomalyAlertsOutput } from "../dto/anomaly-alert.dto";
