/**
 * ClearRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClearRepository Port
 *
 * DDD: Application port for clearrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ClearAnomalyAlertInput, ClearAnomalyAlertOutput } from "../dto/clear.dto";
export interface ClearRepository {
  clearAnomalyAlert(input: ClearAnomalyAlertInput): Promise<ClearAnomalyAlertOutput>;
}

export type { ClearAnomalyAlertInput, ClearAnomalyAlertOutput } from "../dto/clear.dto";
