/**
 * Handlers for AuditExport
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ParticipantsDomainModule } from "../dependencies/participants-ddd.dependencies.js";
import type { ListAuditExportsInput, RequestAuditExportInput } from "@oncepass/services/participants";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/audit-exports
 * Operation: listAuditExports
 */
export async function listAuditExports(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ParticipantsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAuditExportsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.auditExports.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/audit-exports
 * Operation: requestAuditExport
 */
export async function requestAuditExport(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ParticipantsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RequestAuditExportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.auditExports.get.execute(input);
  return reply.code(201).send(result);
}


