/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Erasures Domain Use Cases
 * 
 * List of all use case names for the erasures domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ERASURES_USE_CASES = [
  "executeExecuteVaultErasure",
  "executeGetErasureEvent",
  "executeListErasureEvents"
] as const;
