/**
 * ExecuteGetErasureEvent - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetErasureEvent Use Case
 *
 * DDD: Application use case for get Erasure.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetErasureEventInput, GetErasureEventOutput } from "../dto/erasure.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { ErasureRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetErasureEvent {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly erasure: ErasureRepository
  ) {}

  async execute(input: GetErasureEventInput): Promise<GetErasureEventOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ersId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).erasureId) {
      throw new ValidationError("erasureId is required");
    }
    const erasureId = (input as any).erasureId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.erasure.getErasureEvent({ erasureId: erasureId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${erasureId}`);
    }

    return entity as GetErasureEventOutput;
  }
}
