/**
 * Handlers for Erasure
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ErasuresDomainModule } from "../dependencies/erasures-ddd.dependencies.js";
import type { ExecuteVaultErasureInput, GetErasureEventInput, ListErasureEventsInput } from "@oncepass/services/erasures";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/erasures
 * Operation: listErasureEvents
 */
export async function listErasureEvents(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], vaultId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ErasuresDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListErasureEventsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.erasures.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/erasures
 * Operation: executeVaultErasure
 */
export async function executeVaultErasure(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ErasuresDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ExecuteVaultErasureInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.erasures.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/erasures/{erasureId}
 * Operation: getErasureEvent
 */
export async function getErasureEvent(
  request: FastifyRequest<{ Params: { erasureId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ErasuresDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetErasureEventInput = {
    erasureId: request.params.erasureId,
  };
  const result = await deps.useCases.erasures.get.execute(input);
  return reply.code(200).send(result);
}


