/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as accessRoutes from "../../domains/access/routes/index.js";
import * as consentsRoutes from "../../domains/consents/routes/index.js";
import * as erasuresRoutes from "../../domains/erasures/routes/index.js";
import * as evidenceRoutes from "../../domains/evidence/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as participantsRoutes from "../../domains/participants/routes/index.js";
import * as vaultsRoutes from "../../domains/vaults/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "access", mod: accessRoutes },
  { domain: "consents", mod: consentsRoutes },
  { domain: "erasures", mod: erasuresRoutes },
  { domain: "evidence", mod: evidenceRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "participants", mod: participantsRoutes },
  { domain: "vaults", mod: vaultsRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
