/**
 * Routes for Erasure
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { executeVaultErasure, getErasureEvent, listErasureEvents } from "../handlers/erasure.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function erasureRoutes(fastify: FastifyInstance) {
  // POST /v1/erasures (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/erasures",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getErasuresDependenciesForRequest();
        await executeVaultErasure(request, reply, deps);
      });
    }
  );


  // GET /v1/erasures (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/erasures",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getErasuresDependenciesForRequest();
        await listErasureEvents(request, reply, deps);
      });
    }
  );


  // GET /v1/erasures/{erasureId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/erasures/:erasureId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { erasureId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getErasuresDependenciesForRequest();
        await getErasureEvent(request, reply, deps);
      });
    }
  );


}
