/**
 * AnomalyAlertRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnomalyAlertRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AnomalyAlertRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AnomalyAlertRepository,
} from "@oncepass/services/participants";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AnomalyAlertRepositoryDdb } from "./anomaly-alert-repository.ddb.js";

/**
 * AnomalyAlertRepositoryAdapter
 *
 * Implements AnomalyAlertRepository port for infrastructure layer.
 */
export class AnomalyAlertRepositoryAdapter implements AnomalyAlertRepository {
  private readonly ddb: AnomalyAlertRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AnomalyAlertRepositoryDdb(this.dynamoClient);
  }

  async listAnomalyAlerts(input: Parameters<AnomalyAlertRepository['listAnomalyAlerts']>[0]): Promise<Awaited<ReturnType<AnomalyAlertRepository['listAnomalyAlerts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAnomalyAlerts(input);
  }
}
