/**
 * AuditExportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditExportRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AuditExportRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AuditExportRepository,
} from "@oncepass/services/participants";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AuditExportRepositoryDdb } from "./audit-export-repository.ddb.js";

/**
 * AuditExportRepositoryAdapter
 *
 * Implements AuditExportRepository port for infrastructure layer.
 */
export class AuditExportRepositoryAdapter implements AuditExportRepository {
  private readonly ddb: AuditExportRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AuditExportRepositoryDdb(this.dynamoClient);
  }

  async listAuditExports(input: Parameters<AuditExportRepository['listAuditExports']>[0]): Promise<Awaited<ReturnType<AuditExportRepository['listAuditExports']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAuditExports(input);
  }

  async requestAuditExport(input: Parameters<AuditExportRepository['requestAuditExport']>[0]): Promise<Awaited<ReturnType<AuditExportRepository['requestAuditExport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requestAuditExport(input);
  }
}
