/**
 * ReuseMetricRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReuseMetricRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReuseMetricRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReuseMetricRepository,
} from "@oncepass/services/participants";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReuseMetricRepositoryDdb } from "./reuse-metric-repository.ddb.js";

/**
 * ReuseMetricRepositoryAdapter
 *
 * Implements ReuseMetricRepository port for infrastructure layer.
 */
export class ReuseMetricRepositoryAdapter implements ReuseMetricRepository {
  private readonly ddb: ReuseMetricRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReuseMetricRepositoryDdb(this.dynamoClient);
  }

  async getReuseMetrics(input: Parameters<ReuseMetricRepository['getReuseMetrics']>[0]): Promise<Awaited<ReturnType<ReuseMetricRepository['getReuseMetrics']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getReuseMetrics(input);
  }
}
