/**
 * ExecuteListHomeVaults - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListHomeVaults Use Case
 *
 * DDD: Application use case for list Vault.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListHomeVaultsInput, ListHomeVaultsOutput } from "../dto/vault.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { VaultRepository } from "../ports";

export class ExecuteListHomeVaults {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly vault: VaultRepository
  ) {}

  async execute(input: ListHomeVaultsInput): Promise<ListHomeVaultsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vltId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.vault.listHomeVaults({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListHomeVaultsOutput;
  }
}
