/**
 * ExecuteGetHomeVault - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetHomeVault Use Case
 *
 * DDD: Application use case for get Vault.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetHomeVaultInput, GetHomeVaultOutput } from "../dto/vault.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { VaultRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetHomeVault {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly vault: VaultRepository
  ) {}

  async execute(input: GetHomeVaultInput): Promise<GetHomeVaultOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vltId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).vaultId) {
      throw new ValidationError("vaultId is required");
    }
    const vaultId = (input as any).vaultId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.vault.getHomeVault({ vaultId: vaultId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${vaultId}`);
    }

    return entity as GetHomeVaultOutput;
  }
}
