/**
 * ListAccessRequest DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAccessRequestsParams } from "@oncepass/core/access";

export function createListAccessRequestRequest(overrides: Partial<ListAccessRequestsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
