/**
 * Handlers for Vault
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { VaultsDomainModule } from "../dependencies/vaults-ddd.dependencies.js";
import type { GetHomeVaultInput, ListHomeVaultsInput, RefreshHomeVaultCompletenessInput, RegisterHomeVaultInput } from "@oncepass/services/vaults";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/vaults
 * Operation: listHomeVaults
 */
export async function listHomeVaults(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], institutionId?: string | string[], subjectRef?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: VaultsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListHomeVaultsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.vaults.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/vaults
 * Operation: registerHomeVault
 */
export async function registerHomeVault(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: VaultsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterHomeVaultInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.vaults.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/vaults/{vaultId}
 * Operation: getHomeVault
 */
export async function getHomeVault(
  request: FastifyRequest<{ Params: { vaultId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: VaultsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetHomeVaultInput = {
    vaultId: request.params.vaultId,
  };
  const result = await deps.useCases.vaults.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/vaults/{vaultId}
 * Operation: refreshHomeVaultCompleteness
 */
export async function refreshHomeVaultCompleteness(
  request: FastifyRequest<{ Params: { vaultId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: VaultsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RefreshHomeVaultCompletenessInput = {
    vaultId: request.params.vaultId,
  };
  const result = await deps.useCases.vaults.update.execute(input);
  return reply.code(200).send(result);
}


