/**
 * UpdateVault DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RefreshHomeVaultCompletenessParams } from "@oncepass/core/vaults";

export function createUpdateVaultRequest(overrides: Partial<RefreshHomeVaultCompletenessParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
