/**
 * Vaults DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Vaults Domain Module - Composition root
 *
 * DDD: Composition root for vaults domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  VaultRepositoryAdapter,
} from "@oncepass/adapters/vaults";
import { getIdGeneratorService } from "@oncepass/adapters";
import type { AdapterDynamoDBClient } from "@oncepass/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetHomeVault,
  ExecuteListHomeVaults,
  ExecuteRefreshHomeVaultCompleteness,
  ExecuteRegisterHomeVault,
} from "@oncepass/services/vaults/usecases";
// Ports (interfaces)
import type {
  VaultRepository,
} from "@oncepass/services/vaults/ports";

export interface VaultsDomainModule {
  repos: {
    vaults: VaultRepository;
  };
  useCases: {
    vaults: {
      create: ExecuteRegisterHomeVault;
      get: ExecuteGetHomeVault;
      list: ExecuteListHomeVaults;
      update: ExecuteRefreshHomeVaultCompleteness;
    };
  };
}

export function buildVaultsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): VaultsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      vaults?: VaultRepository;
    } = {};

    obj.vaults = new VaultRepositoryAdapter(dynamoClient);
    return {
      vaults: obj.vaults!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    vaults: {
      create: new ExecuteRegisterHomeVault(executionContext, idGenerator, repos.vaults),
      get: new ExecuteGetHomeVault(executionContext, idGenerator, repos.vaults),
      list: new ExecuteListHomeVaults(executionContext, idGenerator, repos.vaults),
      update: new ExecuteRefreshHomeVaultCompleteness(executionContext, idGenerator, repos.vaults),
    },
  };
  return { repos, useCases: useCases as VaultsDomainModule["useCases"] };
}
