/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./execute-vault-erasure.handler.test.js";
export * from "./get-erasure-event.handler.test.js";
export * from "./list-erasure-events.handler.test.js";
