/**
 * ListErasureEvents handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listErasureEvents } from "@oncepass/api-server/domains/erasures/handlers";
import type { ErasuresDDDDependencies } from "@oncepass/api-server/domains/erasures";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@oncepass/tests/shared";
import { ERASURES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListErasureEvents", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ErasuresDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ErasuresDDDDependencies>(
      ERASURES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      { id: 'mock-1', orgId } as any,
      { id: 'mock-2', orgId } as any,
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListErasureEvents, "execute").mockResolvedValue(useCaseResult);

    await listErasureEvents(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListErasureEvents.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
