/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./get-home-vault.handler.test.js";
export * from "./list-home-vaults.handler.test.js";
export * from "./refresh-home-vault-completeness.handler.test.js";
export * from "./register-home-vault.handler.test.js";
