/**
 * RefreshHomeVaultCompleteness handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { refreshHomeVaultCompleteness } from "@oncepass/api-server/domains/vaults/handlers";
import type { VaultsDDDDependencies } from "@oncepass/api-server/domains/vaults";
import { createUpdateVaultRequest } from "@oncepass/factories/vaults";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@oncepass/tests/shared";
import { VAULTS_USE_CASES } from "../__factories__/use-cases.js";

describe("RefreshHomeVaultCompleteness", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VaultsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VaultsDDDDependencies>(
      VAULTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = createUpdateVaultRequest();
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { vaultId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRefreshHomeVaultCompleteness, "execute").mockResolvedValue(useCaseResult);

    await refreshHomeVaultCompleteness(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRefreshHomeVaultCompleteness.execute).toHaveBeenCalledWith(expect.objectContaining({ vaultId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
