/**
 * RegisterHomeVault handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { registerHomeVault } from "@oncepass/api-server/domains/vaults/handlers";
import type { VaultsDDDDependencies } from "@oncepass/api-server/domains/vaults";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@oncepass/tests/shared";
import { VAULTS_USE_CASES } from "../__factories__/use-cases.js";

describe("RegisterHomeVault", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VaultsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VaultsDDDDependencies>(
      VAULTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRegisterHomeVault, "execute").mockResolvedValue(useCaseResult);

    await registerHomeVault(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRegisterHomeVault.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
