/**
 * AnomalyAlert DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnomalyAlert DTOs
 *
 * DDD: Application DTOs for AnomalyAlert use cases.
 */

import type { ListAnomalyAlertsParams } from "@oncepass/core/participants/types";

export type ListAnomalyAlertsInput = ListAnomalyAlertsParams;

export type ListAnomalyAlertsOutput = {};
