/**
 * AuditExport DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditExport DTOs
 *
 * DDD: Application DTOs for AuditExport use cases.
 */

import type { ListAuditExportsParams, RequestAuditExportRequestInput } from "@oncepass/core/participants/types";

export type ListAuditExportsInput = ListAuditExportsParams;

export type RequestAuditExportInput = RequestAuditExportRequestInput;

export type ListAuditExportsOutput = {};

export type RequestAuditExportOutput = {};
