/**
 * Clear DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Clear DTOs
 *
 * DDD: Application DTOs for Clear use cases.
 */

import type { ClearAnomalyAlertParams, ClearAnomalyAlertRequestInput } from "@oncepass/core/participants/types";

export type ClearAnomalyAlertInput = ClearAnomalyAlertParams & ClearAnomalyAlertRequestInput;

export type ClearAnomalyAlertOutput = {};
