/**
 * ReuseMetric DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReuseMetric DTOs
 *
 * DDD: Application DTOs for ReuseMetric use cases.
 */

import type { GetReuseMetricsParams } from "@oncepass/core/participants/types";

export type GetReuseMetricsInput = GetReuseMetricsParams;

export type GetReuseMetricsOutput = {};
