/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @oncepass/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@oncepass/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@oncepass/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@oncepass/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@oncepass/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@oncepass/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _access from "./access/index.js";
import * as _consents from "./consents/index.js";
import * as _erasures from "./erasures/index.js";
import * as _evidence from "./evidence/index.js";
import * as _identity from "./identity/index.js";
import * as _participants from "./participants/index.js";
import * as _vaults from "./vaults/index.js";

// Export as namespaces
export const _shared = __shared;
export const access = _access;
export const consents = _consents;
export const erasures = _erasures;
export const evidence = _evidence;
export const identity = _identity;
export const participants = _participants;
export const vaults = _vaults;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@oncepass/core"; activity.types.*
//   - Direct exports: import * from "@oncepass/core/activity/types/index.js"
//   - Direct exports: import * from "@oncepass/core/activity/repositories/index.js"
//   - Direct exports: import * from "@oncepass/core/activity/models/index.js"
//   - Direct exports: import * from "@oncepass/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Access Service
export { schemas as AccessSchemas } from "./access/schemas/access.schemas.js";

// Consents Service
export { schemas as ConsentsSchemas } from "./consents/schemas/consents.schemas.js";

// Erasures Service
export { schemas as ErasuresSchemas } from "./erasures/schemas/erasures.schemas.js";

// Evidence Service
export { schemas as EvidenceSchemas } from "./evidence/schemas/evidence.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Participants Service
export { schemas as ParticipantsSchemas } from "./participants/schemas/participants.schemas.js";

// Vaults Service
export { schemas as VaultsSchemas } from "./vaults/schemas/vaults.schemas.js";

