/**
 * ExecuteRequestAuditExport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRequestAuditExport Use Case
 *
 * DDD: Application use case for get AuditExport.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RequestAuditExportInput, RequestAuditExportOutput } from "../dto/audit-export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { AuditExportRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteRequestAuditExport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly auditExport: AuditExportRepository
  ) {}

  async execute(input: RequestAuditExportInput): Promise<RequestAuditExportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prtId();

    // All field names extracted from OpenAPI spec: from, orgId, to
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.auditExport.requestAuditExport({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as RequestAuditExportOutput;
  }
}
