/**
 * ExecuteRegisterParticipant - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterParticipant Use Case
 *
 * DDD: Application use case for create Participant.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterParticipantInput, RegisterParticipantOutput } from "../dto/participant.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { ParticipantRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterParticipant {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly participant: ParticipantRepository
  ) {}

  async execute(input: RegisterParticipantInput): Promise<RegisterParticipantOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prtId();

    // All field names extracted from OpenAPI spec: controllership, dpoContact, name, role
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.controllership) {
      throw new ValidationError("controllership is required");
    }
    if (!input.role) {
      throw new ValidationError("role is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (participants domain)
    const entityId = this.idGenerator.prtId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.participant.registerParticipant({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterParticipantOutput;
  }
}
