/**
 * ExecuteListAnomalyAlerts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAnomalyAlerts Use Case
 *
 * DDD: Application use case for list AnomalyAlert.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAnomalyAlertsInput, ListAnomalyAlertsOutput } from "../dto/anomaly-alert.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { AnomalyAlertRepository } from "../ports";

export class ExecuteListAnomalyAlerts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly anomalyAlert: AnomalyAlertRepository
  ) {}

  async execute(input: ListAnomalyAlertsInput): Promise<ListAnomalyAlertsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prtId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.anomalyAlert.listAnomalyAlerts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAnomalyAlertsOutput;
  }
}
