/**
 * ExecuteClearAnomalyAlert - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteClearAnomalyAlert Use Case
 *
 * DDD: Application use case for get Clear.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ClearAnomalyAlertInput, ClearAnomalyAlertOutput } from "../dto/clear.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { ClearRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteClearAnomalyAlert {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly clear: ClearRepository
  ) {}

  async execute(input: ClearAnomalyAlertInput): Promise<ClearAnomalyAlertOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prtId();

    // All field names extracted from OpenAPI spec: reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).anomalyId) {
      throw new ValidationError("anomalyId is required");
    }
    const anomalyId = (input as any).anomalyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.clear.clearAnomalyAlert({ anomalyId: anomalyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${anomalyId}`);
    }

    return entity as ClearAnomalyAlertOutput;
  }
}
