/**
 * ListAnomalyAlerts handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listAnomalyAlerts } from "@oncepass/api-server/domains/participants/handlers";
import type { ParticipantsDDDDependencies } from "@oncepass/api-server/domains/participants";
import { createAnomalyAlert as createAnomalyAlertEntity } from "@oncepass/factories/participants";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@oncepass/tests/shared";
import { PARTICIPANTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListAnomalyAlerts", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ParticipantsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ParticipantsDDDDependencies>(
      PARTICIPANTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createAnomalyAlertEntity({ orgId }),
      createAnomalyAlertEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListAnomalyAlerts, "execute").mockResolvedValue(useCaseResult);

    await listAnomalyAlerts(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListAnomalyAlerts.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
