/**
 * AnomalyAlert Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AnomalyAlertEntity } from "@oncepass/core/participants/models/index.js";
import { participantsSchemas } from "@oncepass/core/participants";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prt";

export function createAnomalyAlert(overrides: Partial<AnomalyAlertEntity> = {}) {
  const raw = {
    id: overrides.id ?? `anm_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    participantId: overrides.participantId ?? `prt_${ulid().toLowerCase()}`,
    severity: overrides.severity ?? "low",
    status: overrides.status ?? "open",
    summary: overrides.summary ?? faker.lorem.word(),
    ...overrides,
  };

  return participantsSchemas.AnomalyAlert.parse(raw);
}

export function anomalyAlertBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAnomalyAlert(overrides));
}
