/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Vaults Domain Use Cases
 * 
 * List of all use case names for the vaults domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const VAULTS_USE_CASES = [
  "executeGetHomeVault",
  "executeListHomeVaults",
  "executeRefreshHomeVaultCompleteness",
  "executeRegisterHomeVault"
] as const;
