/**
 * ExecuteGetEvidence - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetEvidence Use Case
 *
 * DDD: Application use case for get Evidence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetEvidenceInput, GetEvidenceOutput } from "../dto/evidence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { EvidenceRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetEvidence {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly evidence: EvidenceRepository
  ) {}

  async execute(input: GetEvidenceInput): Promise<GetEvidenceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.evdId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).evidenceId) {
      throw new ValidationError("evidenceId is required");
    }
    const evidenceId = (input as any).evidenceId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.evidence.getEvidence({ evidenceId: evidenceId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${evidenceId}`);
    }

    return entity as GetEvidenceOutput;
  }
}
