/**
 * ExecuteNotariseEvidence - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteNotariseEvidence Use Case
 *
 * DDD: Application use case for get Evidence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { NotariseEvidenceInput, NotariseEvidenceOutput } from "../dto/evidence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { EvidenceRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteNotariseEvidence {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly evidence: EvidenceRepository
  ) {}

  async execute(input: NotariseEvidenceInput): Promise<NotariseEvidenceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.evdId();

    // All field names extracted from OpenAPI spec: auditNote, evidenceHash, pdBanPassed, ssiMode, vaultId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).vaultId) {
      throw new ValidationError("vaultId is required");
    }
    const vaultId = (input as any).vaultId;

    // Create evidence via repository with full notarisation payload
    const entity = await this.evidence.notariseEvidence({
      ...(input as object),
      vaultId,
      orgId: this.context.getOrgId(),
      correlationId,
    } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${vaultId}`);
    }

    return entity as NotariseEvidenceOutput;
  }
}
