/**
 * ExecuteListEvidence - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEvidence Use Case
 *
 * DDD: Application use case for list Evidence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEvidenceInput, ListEvidenceOutput } from "../dto/evidence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { EvidenceRepository } from "../ports";

export class ExecuteListEvidence {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly evidence: EvidenceRepository
  ) {}

  async execute(input: ListEvidenceInput): Promise<ListEvidenceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.evdId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.evidence.listEvidence({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEvidenceOutput;
  }
}
