/**
 * AccessRequest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AccessRequest DTOs
 *
 * DDD: Application DTOs for AccessRequest use cases.
 */

import type { GetAccessRequestParams, ListAccessRequestsParams, RequestEvidenceAccessRequestInput } from "@oncepass/core/access/types";

export type ListAccessRequestsInput = ListAccessRequestsParams;

export type RequestEvidenceAccessInput = RequestEvidenceAccessRequestInput;

export type GetAccessRequestInput = GetAccessRequestParams;

export type ListAccessRequestsOutput = {};

export type RequestEvidenceAccessOutput = {};

export type GetAccessRequestOutput = {};
