/**
 * AmlDecision DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AmlDecision DTOs
 *
 * DDD: Application DTOs for AmlDecision use cases.
 */

import type { RecordAmlDecisionParams, RecordAmlDecisionRequestInput } from "@oncepass/core/access/types";

export type RecordAmlDecisionInput = RecordAmlDecisionParams & RecordAmlDecisionRequestInput;

export type RecordAmlDecisionOutput = {};
