/**
 * Consents DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Consents Domain Module - Composition root
 *
 * DDD: Composition root for consents domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ConsentRepositoryAdapter,
  DecideRepositoryAdapter,
  WithdrawRepositoryAdapter,
} from "@oncepass/adapters/consents";
import { getIdGeneratorService } from "@oncepass/adapters";
import type { AdapterDynamoDBClient } from "@oncepass/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateConsentGrant,
  ExecuteDecideConsentGrant,
  ExecuteGetConsentGrant,
  ExecuteListConsentGrants,
  ExecuteWithdrawConsentGrant,
} from "@oncepass/services/consents/usecases";
// Ports (interfaces)
import type {
  ConsentRepository,
  DecideRepository,
  WithdrawRepository,
} from "@oncepass/services/consents/ports";

export interface ConsentsDomainModule {
  repos: {
    consents: ConsentRepository;
    decides: DecideRepository;
    withdraws: WithdrawRepository;
  };
  useCases: {
    consents: {
      create: ExecuteCreateConsentGrant;
      get: ExecuteGetConsentGrant;
      list: ExecuteListConsentGrants;
    };
    decides: {
      get: ExecuteDecideConsentGrant;
    };
    withdraws: {
      get: ExecuteWithdrawConsentGrant;
    };
  };
}

export function buildConsentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ConsentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      consents?: ConsentRepository;
      decides?: DecideRepository;
      withdraws?: WithdrawRepository;
    } = {};

    obj.consents = new ConsentRepositoryAdapter(dynamoClient);
    obj.decides = new DecideRepositoryAdapter(dynamoClient);
    obj.withdraws = new WithdrawRepositoryAdapter(dynamoClient);
    return {
      consents: obj.consents!,
      decides: obj.decides!,
      withdraws: obj.withdraws!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    consents: {
      create: new ExecuteCreateConsentGrant(executionContext, idGenerator, repos.consents),
      get: new ExecuteGetConsentGrant(executionContext, idGenerator, repos.consents),
      list: new ExecuteListConsentGrants(executionContext, idGenerator, repos.consents),
    },
    decides: {
      get: new ExecuteDecideConsentGrant(executionContext, idGenerator, repos.decides),
    },
    withdraws: {
      get: new ExecuteWithdrawConsentGrant(executionContext, idGenerator, repos.withdraws),
    },
  };
  return { repos, useCases: useCases as ConsentsDomainModule["useCases"] };
}
