/**
 * Routes for AmlDecision
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { recordAmlDecision } from "../handlers/aml-decision.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function amlDecisionRoutes(fastify: FastifyInstance) {
  // POST /v1/access-requests/{accessId}/aml-decision (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/access-requests/:accessId/aml-decision",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { accessId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAccessDependenciesForRequest();
        await recordAmlDecision(request, reply, deps);
      });
    }
  );


}
