/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { accessRequestRoutes } from "./access-request.routes.js";
export { amlDecisionRoutes } from "./aml-decision.routes.js";
