/**
 * GetAccessRequest handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAccessRequest } from "@oncepass/api-server/domains/access/handlers";
import type { AccessDDDDependencies } from "@oncepass/api-server/domains/access";
import { createAccessRequest as createAccessRequestEntity } from "@oncepass/factories/access";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@oncepass/tests/shared";
import { ACCESS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAccessRequest", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AccessDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AccessDDDDependencies>(
      ACCESS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createAccessRequestEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAccessRequest, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { accessId: entity.id };

    await getAccessRequest(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAccessRequest.execute).toHaveBeenCalledWith(expect.objectContaining({ accessId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { accessId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetAccessRequest, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getAccessRequest(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
