/**
 * Routes for AuditExport
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listAuditExports, requestAuditExport } from "../handlers/audit-export.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function auditExportRoutes(fastify: FastifyInstance) {
  // GET /v1/audit-exports (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/audit-exports",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getParticipantsDependenciesForRequest();
        await listAuditExports(request, reply, deps);
      });
    }
  );


  // POST /v1/audit-exports (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/audit-exports",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getParticipantsDependenciesForRequest();
        await requestAuditExport(request, reply, deps);
      });
    }
  );


}
