/**
 * Routes for Clear
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { clearAnomalyAlert } from "../handlers/clear.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function clearRoutes(fastify: FastifyInstance) {
  // POST /v1/anomaly-alerts/{anomalyId}/clear (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/anomaly-alerts/:anomalyId/clear",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { anomalyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getParticipantsDependenciesForRequest();
        await clearAnomalyAlert(request, reply, deps);
      });
    }
  );


}
