/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAccessDomainModule } from "./access/dependencies/access-ddd.dependencies.js";
export { buildConsentsDomainModule } from "./consents/dependencies/consents-ddd.dependencies.js";
export { buildErasuresDomainModule } from "./erasures/dependencies/erasures-ddd.dependencies.js";
export { buildEvidenceDomainModule } from "./evidence/dependencies/evidence-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildParticipantsDomainModule } from "./participants/dependencies/participants-ddd.dependencies.js";
export { buildVaultsDomainModule } from "./vaults/dependencies/vaults-ddd.dependencies.js";

// Export all domain dependency types
export type { AccessDomainModule } from "./access/dependencies/access-ddd.dependencies.js";
export type { ConsentsDomainModule } from "./consents/dependencies/consents-ddd.dependencies.js";
export type { ErasuresDomainModule } from "./erasures/dependencies/erasures-ddd.dependencies.js";
export type { EvidenceDomainModule } from "./evidence/dependencies/evidence-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { ParticipantsDomainModule } from "./participants/dependencies/participants-ddd.dependencies.js";
export type { VaultsDomainModule } from "./vaults/dependencies/vaults-ddd.dependencies.js";
