/**
 * ExecuteRequestEvidenceAccess - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRequestEvidenceAccess Use Case
 *
 * DDD: Application use case for get AccessRequest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RequestEvidenceAccessInput, RequestEvidenceAccessOutput } from "../dto/access-request.dto";
import type { ExecutionContextService, IdGeneratorService } from "@oncepass/services/_shared/index.js";
import type { AccessRequestRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRequestEvidenceAccess {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly accessRequest: AccessRequestRepository
  ) {}

  async execute(input: RequestEvidenceAccessInput): Promise<RequestEvidenceAccessOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.accId();

    // All field names extracted from OpenAPI spec: grantId, purpose
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).grantId) {
      throw new ValidationError("grantId is required");
    }
    const grantId = (input as any).grantId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.accessRequest.requestEvidenceAccess({ grantId: grantId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${grantId}`);
    }

    return entity as RequestEvidenceAccessOutput;
  }
}
