/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@oncepass/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@oncepass/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@oncepass/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _access from "./access/index.js";
import * as _consents from "./consents/index.js";
import * as _erasures from "./erasures/index.js";
import * as _evidence from "./evidence/index.js";
import * as _identity from "./identity/index.js";
import * as _participants from "./participants/index.js";
import * as _vaults from "./vaults/index.js";

// Export as namespaces
export const access = _access;
export const consents = _consents;
export const erasures = _erasures;
export const evidence = _evidence;
export const identity = _identity;
export const participants = _participants;
export const vaults = _vaults;
