/**
 * Routes for Evidence
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getEvidence, listEvidence, notariseEvidence } from "../handlers/evidence.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function evidenceRoutes(fastify: FastifyInstance) {
  // GET /v1/evidence (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/evidence",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await listEvidence(request, reply, deps);
      });
    }
  );


  // POST /v1/evidence (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/evidence",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await notariseEvidence(request, reply, deps);
      });
    }
  );


  // GET /v1/evidence/{evidenceId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/evidence/:evidenceId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { evidenceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await getEvidence(request, reply, deps);
      });
    }
  );


}
