/**
 * Routes for SsiTemplate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getSsiTemplate, updateSsiTemplate } from "../handlers/ssi-template.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function ssiTemplateRoutes(fastify: FastifyInstance) {
  // GET /v1/ssi-template (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/ssi-template",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await getSsiTemplate(request, reply, deps);
      });
    }
  );


  // PUT /v1/ssi-template (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/ssi-template",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await updateSsiTemplate(request, reply, deps);
      });
    }
  );


}
