/**
 * EvidenceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidenceRepository Port
 *
 * DDD: Application port for evidencerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetEvidenceInput, GetEvidenceOutput, ListEvidenceInput, ListEvidenceOutput, NotariseEvidenceInput, NotariseEvidenceOutput } from "../dto/evidence.dto";
export interface EvidenceRepository {
  listEvidence(input: ListEvidenceInput): Promise<ListEvidenceOutput>;
  notariseEvidence(input: NotariseEvidenceInput): Promise<NotariseEvidenceOutput>;
  getEvidence(input: GetEvidenceInput): Promise<GetEvidenceOutput>;
}

export type { GetEvidenceInput, GetEvidenceOutput, ListEvidenceInput, ListEvidenceOutput, NotariseEvidenceInput, NotariseEvidenceOutput } from "../dto/evidence.dto";
