/**
 * SsiTemplateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SsiTemplateRepository Port
 *
 * DDD: Application port for ssitemplaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetSsiTemplateInput, GetSsiTemplateOutput, UpdateSsiTemplateInput, UpdateSsiTemplateOutput } from "../dto/ssi-template.dto";
export interface SsiTemplateRepository {
  getSsiTemplate(input: GetSsiTemplateInput): Promise<GetSsiTemplateOutput>;
  updateSsiTemplate(input: UpdateSsiTemplateInput): Promise<UpdateSsiTemplateOutput>;
}

export type { GetSsiTemplateInput, GetSsiTemplateOutput, UpdateSsiTemplateInput, UpdateSsiTemplateOutput } from "../dto/ssi-template.dto";
