/**
 * AmlDecisionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AmlDecisionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AmlDecisionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AmlDecisionRepository,
} from "@oncepass/services/access";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AmlDecisionRepositoryDdb } from "./aml-decision-repository.ddb.js";

/**
 * AmlDecisionRepositoryAdapter
 *
 * Implements AmlDecisionRepository port for infrastructure layer.
 */
export class AmlDecisionRepositoryAdapter implements AmlDecisionRepository {
  private readonly ddb: AmlDecisionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AmlDecisionRepositoryDdb(this.dynamoClient);
  }

  async recordAmlDecision(input: Parameters<AmlDecisionRepository['recordAmlDecision']>[0]): Promise<Awaited<ReturnType<AmlDecisionRepository['recordAmlDecision']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordAmlDecision(input);
  }
}
