/**
 * Routes for Vault
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getHomeVault, listHomeVaults, refreshHomeVaultCompleteness, registerHomeVault } from "../handlers/vault.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function vaultRoutes(fastify: FastifyInstance) {
  // GET /v1/vaults (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/vaults",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVaultsDependenciesForRequest();
        await listHomeVaults(request, reply, deps);
      });
    }
  );


  // POST /v1/vaults (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/vaults",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVaultsDependenciesForRequest();
        await registerHomeVault(request, reply, deps);
      });
    }
  );


  // GET /v1/vaults/{vaultId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/vaults/:vaultId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { vaultId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVaultsDependenciesForRequest();
        await getHomeVault(request, reply, deps);
      });
    }
  );


  // PATCH /v1/vaults/{vaultId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/vaults/:vaultId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { vaultId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVaultsDependenciesForRequest();
        await refreshHomeVaultCompleteness(request, reply, deps);
      });
    }
  );


}
