/**
 * VaultRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vaults
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VaultRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VaultRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VaultRepository,
} from "@oncepass/services/vaults";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VaultRepositoryDdb } from "./vault-repository.ddb.js";

/**
 * VaultRepositoryAdapter
 *
 * Implements VaultRepository port for infrastructure layer.
 */
export class VaultRepositoryAdapter implements VaultRepository {
  private readonly ddb: VaultRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VaultRepositoryDdb(this.dynamoClient);
  }

  async listHomeVaults(input: Parameters<VaultRepository['listHomeVaults']>[0]): Promise<Awaited<ReturnType<VaultRepository['listHomeVaults']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listHomeVaults(input);
  }

  async registerHomeVault(input: Parameters<VaultRepository['registerHomeVault']>[0]): Promise<Awaited<ReturnType<VaultRepository['registerHomeVault']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerHomeVault(input);
  }

  async getHomeVault(input: Parameters<VaultRepository['getHomeVault']>[0]): Promise<Awaited<ReturnType<VaultRepository['getHomeVault']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getHomeVault(input);
  }

  async refreshHomeVaultCompleteness(input: Parameters<VaultRepository['refreshHomeVaultCompleteness']>[0]): Promise<Awaited<ReturnType<VaultRepository['refreshHomeVaultCompleteness']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.refreshHomeVaultCompleteness(input);
  }
}
