/**
 * ErasureRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ErasureRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ErasureRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ErasureRepository,
} from "@oncepass/services/erasures";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ErasureRepositoryDdb } from "./erasure-repository.ddb.js";

/**
 * ErasureRepositoryAdapter
 *
 * Implements ErasureRepository port for infrastructure layer.
 */
export class ErasureRepositoryAdapter implements ErasureRepository {
  private readonly ddb: ErasureRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ErasureRepositoryDdb(this.dynamoClient);
  }

  async listErasureEvents(input: Parameters<ErasureRepository['listErasureEvents']>[0]): Promise<Awaited<ReturnType<ErasureRepository['listErasureEvents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listErasureEvents(input);
  }

  async executeVaultErasure(input: Parameters<ErasureRepository['executeVaultErasure']>[0]): Promise<Awaited<ReturnType<ErasureRepository['executeVaultErasure']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.executeVaultErasure(input);
  }

  async getErasureEvent(input: Parameters<ErasureRepository['getErasureEvent']>[0]): Promise<Awaited<ReturnType<ErasureRepository['getErasureEvent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getErasureEvent(input);
  }
}
