/**
 * Erasure DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: erasures
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Erasure DTOs
 *
 * DDD: Application DTOs for Erasure use cases.
 */

import type { ExecuteVaultErasureRequestInput, GetErasureEventParams, ListErasureEventsParams } from "@oncepass/core/erasures/types";

export type ListErasureEventsInput = ListErasureEventsParams;

export type ExecuteVaultErasureInput = ExecuteVaultErasureRequestInput;

export type GetErasureEventInput = GetErasureEventParams;

export type ListErasureEventsOutput = {};

export type ExecuteVaultErasureOutput = {};

export type GetErasureEventOutput = {};
