/**
 * CreateWithdraw DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { WithdrawConsentGrantParams } from "@oncepass/core/consents";

export function createCreateWithdrawRequest(overrides: Partial<WithdrawConsentGrantParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
