/**
 * AccessRequest Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AccessRequestEntity } from "@oncepass/core/access/models/index.js";
import { accessSchemas } from "@oncepass/core/access";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "acc";

export function createAccessRequest(overrides: Partial<AccessRequestEntity> = {}) {
  const raw = {
    id: overrides.id ?? `acc_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    grantId: overrides.grantId ?? `cns_${ulid().toLowerCase()}`,
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return accessSchemas.AccessRequest.parse(raw);
}

export function accessRequestBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAccessRequest(overrides));
}
