/**
 * Handlers for Evidence
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvidenceDomainModule } from "../dependencies/evidence-ddd.dependencies.js";
import type { GetEvidenceInput, ListEvidenceInput, NotariseEvidenceInput } from "@oncepass/services/evidence";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/evidence
 * Operation: listEvidence
 */
export async function listEvidence(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], vaultId?: string | string[], subjectRef?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEvidenceInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.evidences.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/evidence
 * Operation: notariseEvidence
 */
export async function notariseEvidence(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: NotariseEvidenceInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.evidences.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/evidence/{evidenceId}
 * Operation: getEvidence
 */
export async function getEvidence(
  request: FastifyRequest<{ Params: { evidenceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEvidenceInput = {
    evidenceId: request.params.evidenceId,
  };
  const result = await deps.useCases.evidences.get.execute(input);
  return reply.code(200).send(result);
}


