/**
 * Handlers for SsiTemplate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvidenceDomainModule } from "../dependencies/evidence-ddd.dependencies.js";
import type { GetSsiTemplateInput, UpdateSsiTemplateInput } from "@oncepass/services/evidence";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/ssi-template
 * Operation: getSsiTemplate
 */
export async function getSsiTemplate(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSsiTemplateInput = {};
  const result = await deps.useCases.ssiTemplates.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/ssi-template
 * Operation: updateSsiTemplate
 */
export async function updateSsiTemplate(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateSsiTemplateInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.ssiTemplates.update.execute(input);
  return reply.code(200).send(result);
}


