/**
 * Participants DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Participants Domain Module - Composition root
 *
 * DDD: Composition root for participants domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AnomalyAlertRepositoryAdapter,
  AuditExportRepositoryAdapter,
  ClearRepositoryAdapter,
  ParticipantRepositoryAdapter,
  ReuseMetricRepositoryAdapter,
  SuspendRepositoryAdapter,
} from "@oncepass/adapters/participants";
import { getIdGeneratorService } from "@oncepass/adapters";
import type { AdapterDynamoDBClient } from "@oncepass/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteClearAnomalyAlert,
  ExecuteGetParticipant,
  ExecuteListAnomalyAlerts,
  ExecuteListAuditExports,
  ExecuteListParticipants,
  ExecuteRegisterParticipant,
  ExecuteRequestAuditExport,
  ExecuteSuspendParticipant,
  ExecuteGetReuseMetrics,
} from "@oncepass/services/participants/usecases";
// Ports (interfaces)
import type {
  AnomalyAlertRepository,
  AuditExportRepository,
  ClearRepository,
  ParticipantRepository,
  ReuseMetricRepository,
  SuspendRepository,
} from "@oncepass/services/participants/ports";

export interface ParticipantsDomainModule {
  repos: {
    anomalyAlerts: AnomalyAlertRepository;
    auditExports: AuditExportRepository;
    clears: ClearRepository;
    participants: ParticipantRepository;
    reuseMetrics: ReuseMetricRepository;
    suspends: SuspendRepository;
  };
  useCases: {
    anomalyAlerts: {
      list: ExecuteListAnomalyAlerts;
    };
    auditExports: {
      get: ExecuteRequestAuditExport;
      list: ExecuteListAuditExports;
    };
    clears: {
      get: ExecuteClearAnomalyAlert;
    };
    participants: {
      create: ExecuteRegisterParticipant;
      get: ExecuteGetParticipant;
      list: ExecuteListParticipants;
    };
    reuseMetrics: {
      get: ExecuteGetReuseMetrics;
    };
    suspends: {
      get: ExecuteSuspendParticipant;
    };
  };
}

export function buildParticipantsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ParticipantsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      anomalyAlerts?: AnomalyAlertRepository;
      auditExports?: AuditExportRepository;
      clears?: ClearRepository;
      participants?: ParticipantRepository;
      reuseMetrics?: ReuseMetricRepository;
      suspends?: SuspendRepository;
    } = {};

    obj.anomalyAlerts = new AnomalyAlertRepositoryAdapter(dynamoClient);
    obj.auditExports = new AuditExportRepositoryAdapter(dynamoClient);
    obj.clears = new ClearRepositoryAdapter(dynamoClient);
    obj.participants = new ParticipantRepositoryAdapter(dynamoClient);
    obj.reuseMetrics = new ReuseMetricRepositoryAdapter(dynamoClient);
    obj.suspends = new SuspendRepositoryAdapter(dynamoClient);
    return {
      anomalyAlerts: obj.anomalyAlerts!,
      auditExports: obj.auditExports!,
      clears: obj.clears!,
      participants: obj.participants!,
      reuseMetrics: obj.reuseMetrics!,
      suspends: obj.suspends!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    anomalyAlerts: {
      list: new ExecuteListAnomalyAlerts(executionContext, idGenerator, repos.anomalyAlerts),
    },
    auditExports: {
      get: new ExecuteRequestAuditExport(executionContext, idGenerator, repos.auditExports),
      list: new ExecuteListAuditExports(executionContext, idGenerator, repos.auditExports),
    },
    clears: {
      get: new ExecuteClearAnomalyAlert(executionContext, idGenerator, repos.clears),
    },
    participants: {
      create: new ExecuteRegisterParticipant(executionContext, idGenerator, repos.participants),
      get: new ExecuteGetParticipant(executionContext, idGenerator, repos.participants),
      list: new ExecuteListParticipants(executionContext, idGenerator, repos.participants),
    },
    reuseMetrics: {
      get: new ExecuteGetReuseMetrics(executionContext, idGenerator, repos.reuseMetrics),
    },
    suspends: {
      get: new ExecuteSuspendParticipant(executionContext, idGenerator, repos.suspends),
    },
  };
  return { repos, useCases: useCases as ParticipantsDomainModule["useCases"] };
}
