/**
 * GetSsiTemplate handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getSsiTemplate } from "@oncepass/api-server/domains/evidence/handlers";
import type { EvidenceDDDDependencies } from "@oncepass/api-server/domains/evidence";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@oncepass/tests/shared";
import { EVIDENCE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetSsiTemplate", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EvidenceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EvidenceDDDDependencies>(
      EVIDENCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetSsiTemplate, "execute").mockResolvedValue(useCaseResult);

    await getSsiTemplate(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetSsiTemplate.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
