/**
 * Handlers for Decide
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ConsentsDomainModule } from "../dependencies/consents-ddd.dependencies.js";
import type { DecideConsentGrantInput } from "@oncepass/services/consents";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/consents/{grantId}/decide
 * Operation: decideConsentGrant
 */
export async function decideConsentGrant(
  request: FastifyRequest<{ Params: { grantId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ConsentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DecideConsentGrantInput = {
    grantId: request.params.grantId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.decides.get.execute(input);
  return reply.code(200).send(result);
}


