/**
 * AmlDecisionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: access
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AmlDecisionRepository Port
 *
 * DDD: Application port for amldecisionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RecordAmlDecisionInput, RecordAmlDecisionOutput } from "../dto/aml-decision.dto";
export interface AmlDecisionRepository {
  recordAmlDecision(input: RecordAmlDecisionInput): Promise<RecordAmlDecisionOutput>;
}

export type { RecordAmlDecisionInput, RecordAmlDecisionOutput } from "../dto/aml-decision.dto";
