/**
 * AnomalyAlert Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/participants.openapi.types.js";
import { schemas } from "../schemas/participants.schemas.js";

/**
 * Entity: AnomalyAlertEntity
 * Description: Represents the AnomalyAlert domain model.
 * Source: schemas.AnomalyAlert
 * Type: Domain Entity (API)
 */
export const AnomalyAlertEntitySchema = schemas.AnomalyAlert;
export type AnomalyAlertEntity = components["schemas"]["AnomalyAlert"];
